- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 2
  max_confirm: 3
- id: 400
  key: gravio
  currency: gio
  min_confirm: 5
  max_confirm: 6
- id: 600
  key: doge
  currency: doge
  min_confirm: 5
  max_confirm: 6
- id: 800
  key: ltc
  currency: ltc
  min_confirm: 5
  max_confirm: 6
- id: 1000
  key: ether
  currency: eth
  min_confirm: 5
  max_confirm: 6

- id: 1200
  key: poseidon
  currency: psd
  min_confirm: 4
  max_confirm: 5
- id: 1400
  key: profithunter
  currency: phc
  min_confirm: 5
  max_confirm: 6
- id: 1600
  key: xgoldcoin
  currency: xgc
  min_confirm: 3
  max_confirm: 4
- id: 1800
  key: deviant
  currency: dev
  min_confirm: 5
  max_confirm: 6
- id: 2000
  key: phoboscoin
  currency: pbs
  min_confirm: 4
  max_confirm: 5
- id: 2200
  key: dinero
  currency: din
  min_confirm: 5
  max_confirm: 6
- id: 2400
  key: advance
  currency: adv
  min_confirm: 5
  max_confirm: 6
- id: 2600
  key: dv7coin
  currency: dv7
  min_confirm: 5
  max_confirm: 6
- id: 2800
  key: shekel
  currency: jew
  min_confirm: 5
  max_confirm: 6
- id: 3000
  key: argo
  currency: argo
  min_confirm: 5
  max_confirm: 6
- id: 3200
  key: escrow
  currency: esco
  min_confirm: 5
  max_confirm: 6
- id: 3400
  key: neetcoin
  currency: neet
  min_confirm: 5
  max_confirm: 6
- id: 3600
  key: xylo
  currency: xylo
  min_confirm: 5
  max_confirm: 6
- id: 3800
  key: steepcoin
  currency: steep
  min_confirm: 5
  max_confirm: 6
- id: 4000
  key: bitcoingreen
  currency: bitg
  min_confirm: 5
  max_confirm: 6
- id: 4200
  key: craftr
  currency: crft
  min_confirm: 5
  max_confirm: 6
- id: 4400
  key: enviromint
  currency: env
  min_confirm: 5
  max_confirm: 6
- id: 4600
  key: snowgem
  currency: sng
  min_confirm: 5
  max_confirm: 6
